### ISSUE TITLE
MacOS build broken due to encapsulation

### ISSUE THREAD

**Issue by lukehutch** [toolfactory/narcissus#17]
@Roberto-Gentili Any idea why this build is [failing](https://github.com/toolfactory/narcissus/actions/runs/11791716477/job/32844443018) on macOS?:

```
Error: ROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (injected-nexus-deploy) on project narcissus: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy failed: An API incompatibility was encountered while executing org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy: java.lang.ExceptionInInitializerError: null
Error: ROR] -----------------------------------------------------
Error: ROR] realm =    extension>org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8
Error: ROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[...]
Error: ROR] -----------------------------------------------------: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @3681037
```

**Comment by Roberto-Gentili** [comment]
[Building with JDK 7 fails](https://github.com/toolfactory/narcissus/actions/runs/11792176670/job/32845485617) with the error below: there appears to be an incompatible Maven plugin with this JDK. ave you updated any Maven plugins?

```
constituent[11]: file:/C:/Users/runneradmin/.m2/wrapper/dists/apache-maven-3.8.8-bin/67c30f74/apache-maven-3.8.8/lib/maven-compat-3.8.8.jar
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:53)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:152)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:76)
	Caused by: java.lang.UnsupportedClassVersionError: com/fasterxml/jackson/databind/ObjectMapper: Unsupported major.minor version 52.0
```

> @Roberto-Gentili Any idea why this build is [failing](https://github.com/toolfactory/narcissus/actions/runs/11791716477/job/32844443018) on macOS?:
> 
> ```
> Error: ROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (injected-nexus-deploy) on project narcissus: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy failed: An API incompatibility was encountered while executing org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy: java.lang.ExceptionInInitializerError: null
> Error: ROR] -----------------------------------------------------
> Error: ROR] realm =    extension>org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8
> Error: ROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
> [...]
> Error: ROR] -----------------------------------------------------: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @3681037
> ```

**Comment by lukehutch** [comment]
It was already broken, so I tried updating all the Maven plugins to see if that would fix it...

It looks like the Maven wrapper version needs to be updated, or something?

**Comment by Roberto-Gentili** [comment]
> It was already broken, so I tried updating all the Maven plugins to see if that would fix it...
> 
> It looks like the Maven wrapper version needs to be updated, or something?
Unfortunately I don't know: I abandoned the build test for JDK 7 due to too many problems even if [I do the release build with the version parameter set for compatibility with JDK 7](https://github.com/toolfactory/jvm-driver/blob/4e3539ed348fbdfa3eb8cc0b8895b8bf6ca16cf3/.github/workflows/%5BA%5D%20build%20and%20test%2C%20release%20if%20requested.yml#L266)

**Comment by Roberto-Gentili** [comment]
> It was already broken, so I tried updating all the Maven plugins to see if that would fix it...
> 
> It looks like the Maven wrapper version needs to be updated, or something?

Unfortunately I don't know: I abandoned the build test for JDK 7 due to too many problems even if [I do the release build with the version parameter set for compatibility with JDK 7](https://github.com/toolfactory/jvm-driver/blob/4e3539ed348fbdfa3eb8cc0b8895b8bf6ca16cf3/.github/workflows/%5BA%5D%20build%20and%20test%2C%20release%20if%20requested.yml#L266)

**Comment by lukehutch** [comment]
@Roberto-Gentili @michael-simons OK, the build seems to be fixed. Thanks for your help! Pushing out 1.0.10.

**Comment by michael-simons** [comment]
It's interesting that this failed on JDK 7 :) I explicitly set the Maven Wrapper and Maven versions to work with 7. Seems to be an issue with `nexus-staging-maven-plugin`.

FWIW There's a way to define tool chains in Maven, so that you don't depend on the JDK that is being used to run Maven, but I never used them.

https://maven.apache.org/guides/mini/guide-using-toolchains.html

**Comment by Roberto-Gentili** [comment]
> @Roberto-Gentili @michael-simons OK, the build seems to be fixed. Thanks for your help! Pushing out 1.0.10.

Great! I will release the new version of JVM-Driver as soon as it is available

**Comment by lukehutch** [comment]
Maven now requires a minimum JDK of 7, it seems (or maybe it is Maven-wrapper). I just removed the testing for JDK 7, since I don't have time to mess with this much more!
